SELECT DISTINCT ?item ?dateModified ?itemLabel ?event_type ?countryLabel
 ?main_subject ?language ?short_name ?official_website 
 ?Twitter_username ?WikiCFP_conference_series_ID ?GND_ID  ?Freebase_ID  ?start_time ?end_time

WHERE {
  {
    ?item wdt:P31 wd:Q2495862 .  
    ?item schema:dateModified ?dateModified;
    wdt:P580 ?start_time;
    wdt:P582 ?end_time . 
    BIND ('congress' as ?event_type) 
  }
  UNION
  {
    ?item wdt:P31 wd:Q40444998 .  
    ?item schema:dateModified ?dateModified;
    wdt:P580 ?start_time;
    wdt:P582 ?end_time . 
    BIND ('workshop' as ?event_type) 
  }
  UNION 
  {
    ?item wdt:P31 wd:Q2020153 .  
    ?item schema:dateModified ?dateModified;
    wdt:P580 ?start_time;
    wdt:P582 ?end_time . 
    BIND ('conference' as ?event_type) 
  }
  UNION 
  {
    ?item wdt:P31 wd:Q504703 .  
    ?item schema:dateModified ?dateModified;
    wdt:P580 ?start_time;
    wdt:P582 ?end_time . 
    BIND ('seminar' as ?event_type) 
  }  
  UNION
  {
    ?item wdt:P31 wd:Q46855.
    ?item schema:dateModified ?dateModified;
    wdt:P580 ?start_time;
    wdt:P582 ?end_time . 
    BIND ('hackthon' as ?event_type )
  }
	
	OPTIONAL { ?item wdt:P921 ?main_subject . }
	OPTIONAL { ?item wdt:P2936 ?language_used . }
	OPTIONAL { ?item wdt:P1813 ?short_name . }
  OPTIONAL  {?item wdt:P17 ?country . }
	OPTIONAL { ?item wdt:P856 ?official_website . }
	OPTIONAL { ?item wdt:P2002 ?Twitter_username . }
	OPTIONAL { ?item wdt:P227 ?GND_ID . }
	OPTIONAL { ?item wdt:P5127 ?WikiCFP_conference_series_IDvalue .
		BIND ( CONCAT("http://wikicfp.com/cfp/program?id=", STR(?WikiCFP_conference_series_IDvalue)) AS ?WikiCFP_conference_series_ID )
	}
	OPTIONAL { ?item wdt:P646 ?Freebase_IDvalue .
	     BIND ( CONCAT("https://freebase.toolforge.org", STR(?Freebase_IDvalue)) AS ?Freebase_ID )
	}

	SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }

}
ORDER BY DESC(?dateModified)



